// <auto-generated />
using System;
using Galaxi.Functions.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galaxi.Functions.Persistence.Migrations
{
    [DbContext(typeof(FunctionContextDb))]
    [Migration("20240903225327_addGuid")]
    partial class addGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Galaxi.Functions.Data.Models.Function", b =>
                {
                    b.Property<Guid>("FunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FunctionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.HasKey("FunctionId");

                    b.ToTable("MovieFunction", "DBO");

                    b.HasData(
                        new
                        {
                            FunctionId = new Guid("ff116ad1-2527-4eac-92dc-97838d61ee7e"),
                            FunctionDate = new DateTime(2024, 9, 3, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7e9c40da-756a-44c4-a84f-580d01b4db1b"),
                            NumberOfSeats = 100,
                            Price = 10.50m,
                            Room = 1
                        },
                        new
                        {
                            FunctionId = new Guid("7666f4a4-608a-4791-892e-82b7bfb08668"),
                            FunctionDate = new DateTime(2024, 9, 3, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("b8fb2e1e-d07b-4838-b103-28985b56305d"),
                            NumberOfSeats = 120,
                            Price = 12.00m,
                            Room = 2
                        },
                        new
                        {
                            FunctionId = new Guid("e498d71c-c2cd-47a2-8f81-b4f9ba95a4c8"),
                            FunctionDate = new DateTime(2024, 9, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("88e4a35e-15e2-4e40-b176-221d213bd2f7"),
                            NumberOfSeats = 150,
                            Price = 15.00m,
                            Room = 3
                        },
                        new
                        {
                            FunctionId = new Guid("ecd93d28-035f-4219-a958-d618627e426f"),
                            FunctionDate = new DateTime(2024, 9, 5, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("2dacbeac-df0f-438c-9def-68eaa914670b"),
                            NumberOfSeats = 80,
                            Price = 8.00m,
                            Room = 4
                        },
                        new
                        {
                            FunctionId = new Guid("92c48606-23c0-46d6-b4bb-aa4f47b18d1e"),
                            FunctionDate = new DateTime(2024, 9, 6, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("01868b3c-3a19-458c-815e-824364b244bd"),
                            NumberOfSeats = 200,
                            Price = 18.50m,
                            Room = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
